import { SnapshotRecord, PhcMaster, KpiSummary, TransferPlanItem, SupplyAlert, FederatedMetrics } from '@/types/supply-chain';

export const PHC_MASTERS: PhcMaster[] = [
  // MADHYA PRADESH
  {
    phc_id: "PHC-MP-001",
    phc_name: "PHC Rampur",
    state: "Madhya Pradesh",
    district: "Dewas",
    lat: 22.9676,
    lon: 76.0534,
    district_warehouse_id: "DW-MP-DEWAS",
    km_to_district_warehouse: 34.5,
    total_beds: 6,
    staff_sanctioned: 5,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-MP-002",
    phc_name: "PHC Bagli",
    state: "Madhya Pradesh",
    district: "Dewas",
    lat: 22.6450,
    lon: 76.3530,
    district_warehouse_id: "DW-MP-DEWAS",
    km_to_district_warehouse: 48.0,
    total_beds: 10,
    staff_sanctioned: 8,
    type: "Community Health Centre",
  },
  {
    phc_id: "PHC-MP-003",
    phc_name: "PHC Kanadia",
    state: "Madhya Pradesh",
    district: "Indore",
    lat: 22.7196,
    lon: 75.9242,
    district_warehouse_id: "DW-MP-INDORE",
    km_to_district_warehouse: 14.2,
    total_beds: 8,
    staff_sanctioned: 6,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-MP-004",
    phc_name: "PHC Sanwer",
    state: "Madhya Pradesh",
    district: "Indore",
    lat: 22.9774,
    lon: 75.8282,
    district_warehouse_id: "DW-MP-INDORE",
    km_to_district_warehouse: 32.0,
    total_beds: 6,
    staff_sanctioned: 5,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-MP-005",
    phc_name: "PHC Badnagar",
    state: "Madhya Pradesh",
    district: "Ujjain",
    lat: 23.0645,
    lon: 75.3814,
    district_warehouse_id: "DW-MP-UJJAIN",
    km_to_district_warehouse: 44.0,
    total_beds: 6,
    staff_sanctioned: 4,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-MP-006",
    phc_name: "PHC Bichhiya",
    state: "Madhya Pradesh",
    district: "Mandla",
    lat: 22.4500,
    lon: 80.7000,
    district_warehouse_id: "DW-MP-MANDLA",
    km_to_district_warehouse: 52.0,
    total_beds: 8,
    staff_sanctioned: 6,
    type: "Tribal PHC",
  },

  // MAHARASHTRA
  {
    phc_id: "PHC-MH-001",
    phc_name: "PHC Khed",
    state: "Maharashtra",
    district: "Pune",
    lat: 18.8500,
    lon: 73.9100,
    district_warehouse_id: "DW-MH-PUNE",
    km_to_district_warehouse: 38.0,
    total_beds: 8,
    staff_sanctioned: 6,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-MH-002",
    phc_name: "PHC Junnar",
    state: "Maharashtra",
    district: "Pune",
    lat: 19.2000,
    lon: 73.8800,
    district_warehouse_id: "DW-MH-PUNE",
    km_to_district_warehouse: 78.5,
    total_beds: 12,
    staff_sanctioned: 10,
    type: "Community Health Centre",
  },
  {
    phc_id: "PHC-MH-003",
    phc_name: "PHC Karad Rural",
    state: "Maharashtra",
    district: "Satara",
    lat: 17.2889,
    lon: 74.2000,
    district_warehouse_id: "DW-MH-SATARA",
    km_to_district_warehouse: 50.0,
    total_beds: 8,
    staff_sanctioned: 6,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-MH-004",
    phc_name: "PHC Wai",
    state: "Maharashtra",
    district: "Satara",
    lat: 17.9500,
    lon: 73.8900,
    district_warehouse_id: "DW-MH-SATARA",
    km_to_district_warehouse: 36.0,
    total_beds: 6,
    staff_sanctioned: 5,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-MH-005",
    phc_name: "PHC Saoner",
    state: "Maharashtra",
    district: "Nagpur",
    lat: 21.3850,
    lon: 78.9150,
    district_warehouse_id: "DW-MH-NAGPUR",
    km_to_district_warehouse: 38.2,
    total_beds: 10,
    staff_sanctioned: 8,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-MH-006",
    phc_name: "PHC Dhadgaon",
    state: "Maharashtra",
    district: "Nandurbar",
    lat: 21.8300,
    lon: 74.2500,
    district_warehouse_id: "DW-MH-NANDURBAR",
    km_to_district_warehouse: 68.0,
    total_beds: 8,
    staff_sanctioned: 6,
    type: "Tribal PHC",
  },

  // KERALA
  {
    phc_id: "PHC-KL-001",
    phc_name: "PHC Meppadi",
    state: "Kerala",
    district: "Wayanad",
    lat: 11.5500,
    lon: 76.1200,
    district_warehouse_id: "DW-KL-WAYANAD",
    km_to_district_warehouse: 22.0,
    total_beds: 8,
    staff_sanctioned: 7,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-KL-002",
    phc_name: "PHC Sultan Bathery",
    state: "Kerala",
    district: "Wayanad",
    lat: 11.6600,
    lon: 76.2600,
    district_warehouse_id: "DW-KL-WAYANAD",
    km_to_district_warehouse: 24.5,
    total_beds: 12,
    staff_sanctioned: 10,
    type: "Community Health Centre",
  },
  {
    phc_id: "PHC-KL-003",
    phc_name: "PHC Vithura",
    state: "Kerala",
    district: "Thiruvananthapuram",
    lat: 8.6800,
    lon: 77.0600,
    district_warehouse_id: "DW-KL-TVM",
    km_to_district_warehouse: 36.0,
    total_beds: 8,
    staff_sanctioned: 6,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-KL-004",
    phc_name: "PHC Nedumangad",
    state: "Kerala",
    district: "Thiruvananthapuram",
    lat: 8.6000,
    lon: 76.9900,
    district_warehouse_id: "DW-KL-TVM",
    km_to_district_warehouse: 18.0,
    total_beds: 10,
    staff_sanctioned: 8,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-KL-005",
    phc_name: "PHC Attappadi",
    state: "Kerala",
    district: "Palakkad",
    lat: 11.0800,
    lon: 76.6200,
    district_warehouse_id: "DW-KL-PALAKKAD",
    km_to_district_warehouse: 72.0,
    total_beds: 12,
    staff_sanctioned: 9,
    type: "Tribal PHC",
  },

  // ASSAM
  {
    phc_id: "PHC-AS-001",
    phc_name: "PHC Hajo",
    state: "Assam",
    district: "Kamrup",
    lat: 26.2400,
    lon: 91.5300,
    district_warehouse_id: "DW-AS-KAMRUP",
    km_to_district_warehouse: 30.0,
    total_beds: 10,
    staff_sanctioned: 7,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-AS-002",
    phc_name: "PHC Boko",
    state: "Assam",
    district: "Kamrup",
    lat: 25.9800,
    lon: 91.2200,
    district_warehouse_id: "DW-AS-KAMRUP",
    km_to_district_warehouse: 58.0,
    total_beds: 8,
    staff_sanctioned: 6,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-AS-003",
    phc_name: "PHC Lakhipur",
    state: "Assam",
    district: "Cachar",
    lat: 24.8000,
    lon: 93.0100,
    district_warehouse_id: "DW-AS-CACHAR",
    km_to_district_warehouse: 28.0,
    total_beds: 10,
    staff_sanctioned: 8,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-AS-004",
    phc_name: "PHC Dholai",
    state: "Assam",
    district: "Cachar",
    lat: 24.6000,
    lon: 92.8500,
    district_warehouse_id: "DW-AS-CACHAR",
    km_to_district_warehouse: 34.0,
    total_beds: 6,
    staff_sanctioned: 5,
    type: "Rural PHC",
  },
  {
    phc_id: "PHC-AS-005",
    phc_name: "PHC Silapathar",
    state: "Assam",
    district: "Dhemaji",
    lat: 27.5900,
    lon: 94.7200,
    district_warehouse_id: "DW-AS-DHEMAJI",
    km_to_district_warehouse: 46.0,
    total_beds: 8,
    staff_sanctioned: 6,
    type: "Flood-Prone PHC",
  },
  {
    phc_id: "PHC-AS-006",
    phc_name: "PHC Jonai",
    state: "Assam",
    district: "Dhemaji",
    lat: 27.9800,
    lon: 95.2200,
    district_warehouse_id: "DW-AS-DHEMAJI",
    km_to_district_warehouse: 88.0,
    total_beds: 8,
    staff_sanctioned: 6,
    type: "Flood-Prone PHC",
  },
];

// Snapshot inventory records matching the required schema
export const INITIAL_SNAPSHOT_RECORDS: SnapshotRecord[] = [
  // 1. Critical shortage at PHC Rampur (MP)
  {
    phc_id: "PHC-MP-001",
    phc_name: "PHC Rampur",
    state: "Madhya Pradesh",
    district: "Dewas",
    medicine: "Paracetamol 500mg tab",
    disease_class: "fever_vector",
    stock: 500,
    unit: "tablets",
    daily_demand: 200,
    days_of_cover: 2.5,
    risk_level: "Critical",
    nearest_expiry: "2027-04-30",
    cold_chain: false,
    beds_available: 2,
    total_beds: 6,
    staff_present: 3,
    staff_sanctioned: 5,
    reporting_status: "reported_today",
    last_updated: "Today, 08:30 AM",
  },
  {
    phc_id: "PHC-MP-001",
    phc_name: "PHC Rampur",
    state: "Madhya Pradesh",
    district: "Dewas",
    medicine: "ORS sachet",
    disease_class: "diarrhoeal",
    stock: 45,
    unit: "packs",
    daily_demand: 25,
    days_of_cover: 1.8,
    risk_level: "Critical",
    nearest_expiry: "2027-08-15",
    cold_chain: false,
    beds_available: 2,
    total_beds: 6,
    staff_present: 3,
    staff_sanctioned: 5,
    reporting_status: "reported_today",
    last_updated: "Today, 08:30 AM",
  },
  // Surplus pairing at PHC Kanadia (MP) - expiring in 65 days
  {
    phc_id: "PHC-MP-003",
    phc_name: "PHC Kanadia",
    state: "Madhya Pradesh",
    district: "Indore",
    medicine: "Paracetamol 500mg tab",
    disease_class: "fever_vector",
    stock: 9200,
    unit: "tablets",
    daily_demand: 150,
    days_of_cover: 61.3,
    risk_level: "Low",
    nearest_expiry: "2026-12-05", // <90 days! Surplus at risk
    cold_chain: false,
    beds_available: 5,
    total_beds: 8,
    staff_present: 5,
    staff_sanctioned: 6,
    reporting_status: "reported_today",
    last_updated: "Today, 09:15 AM",
  },
  {
    phc_id: "PHC-MP-003",
    phc_name: "PHC Kanadia",
    state: "Madhya Pradesh",
    district: "Indore",
    medicine: "ORS sachet",
    disease_class: "diarrhoeal",
    stock: 2800,
    unit: "packs",
    daily_demand: 40,
    days_of_cover: 70.0,
    risk_level: "Low",
    nearest_expiry: "2026-11-20", // <90 days!
    cold_chain: false,
    beds_available: 5,
    total_beds: 8,
    staff_present: 5,
    staff_sanctioned: 6,
    reporting_status: "reported_today",
    last_updated: "Today, 09:15 AM",
  },
  // High risk at Sanwer (MP)
  {
    phc_id: "PHC-MP-004",
    phc_name: "PHC Sanwer",
    state: "Madhya Pradesh",
    district: "Indore",
    medicine: "Paracetamol 500mg tab",
    disease_class: "fever_vector",
    stock: 1200,
    unit: "tablets",
    daily_demand: 200,
    days_of_cover: 6.0,
    risk_level: "High",
    nearest_expiry: "2027-02-28",
    cold_chain: false,
    beds_available: 3,
    total_beds: 6,
    staff_present: 4,
    staff_sanctioned: 5,
    reporting_status: "reported_today",
    last_updated: "Today, 07:45 AM",
  },
  // Critical Anti-Snake Venom in Mandla tribal belt
  {
    phc_id: "PHC-MP-006",
    phc_name: "PHC Bichhiya",
    state: "Madhya Pradesh",
    district: "Mandla",
    medicine: "Anti-snake venom vial",
    disease_class: "emergency_trauma",
    stock: 8,
    unit: "vials",
    daily_demand: 3,
    days_of_cover: 2.6,
    risk_level: "Critical",
    nearest_expiry: "2026-11-30",
    cold_chain: true,
    beds_available: 2,
    total_beds: 8,
    staff_present: 5,
    staff_sanctioned: 6,
    reporting_status: "reported_today",
    last_updated: "Today, 09:00 AM",
  },

  // MAHARASHTRA
  {
    phc_id: "PHC-MH-001",
    phc_name: "PHC Khed",
    state: "Maharashtra",
    district: "Pune",
    medicine: "Amoxicillin 500mg cap",
    disease_class: "respiratory",
    stock: 140,
    unit: "strips",
    daily_demand: 45,
    days_of_cover: 3.1,
    risk_level: "Critical",
    nearest_expiry: "2027-01-10",
    cold_chain: false,
    beds_available: 3,
    total_beds: 8,
    staff_present: 5,
    staff_sanctioned: 6,
    reporting_status: "reported_today",
    last_updated: "Today, 08:10 AM",
  },
  {
    phc_id: "PHC-MH-002",
    phc_name: "PHC Junnar",
    state: "Maharashtra",
    district: "Pune",
    medicine: "Amoxicillin 500mg cap",
    disease_class: "respiratory",
    stock: 1800,
    unit: "strips",
    daily_demand: 30,
    days_of_cover: 60.0,
    risk_level: "Low",
    nearest_expiry: "2026-11-15", // <90 days surplus!
    cold_chain: false,
    beds_available: 8,
    total_beds: 12,
    staff_present: 9,
    staff_sanctioned: 10,
    reporting_status: "reported_today",
    last_updated: "Today, 09:30 AM",
  },
  {
    phc_id: "PHC-MH-003",
    phc_name: "PHC Karad Rural",
    state: "Maharashtra",
    district: "Satara",
    medicine: "Paracetamol 500mg tab",
    disease_class: "fever_vector",
    stock: 450,
    unit: "tablets",
    daily_demand: 180,
    days_of_cover: 2.5,
    risk_level: "Critical",
    nearest_expiry: "2027-06-30",
    cold_chain: false,
    beds_available: 2,
    total_beds: 8,
    staff_present: 4,
    staff_sanctioned: 6,
    reporting_status: "reported_today",
    last_updated: "Today, 08:50 AM",
  },
  {
    phc_id: "PHC-MH-004",
    phc_name: "PHC Wai",
    state: "Maharashtra",
    district: "Satara",
    medicine: "Paracetamol 500mg tab",
    disease_class: "fever_vector",
    stock: 3500,
    unit: "tablets",
    daily_demand: 80,
    days_of_cover: 43.7,
    risk_level: "Low",
    nearest_expiry: "2027-09-15",
    cold_chain: false,
    beds_available: 4,
    total_beds: 6,
    staff_present: 4,
    staff_sanctioned: 5,
    reporting_status: "reported_today",
    last_updated: "Today, 07:30 AM",
  },
  {
    phc_id: "PHC-MH-006",
    phc_name: "PHC Dhadgaon",
    state: "Maharashtra",
    district: "Nandurbar",
    medicine: "Anti-snake venom vial",
    disease_class: "emergency_trauma",
    stock: 6,
    unit: "vials",
    daily_demand: 2,
    days_of_cover: 3.0,
    risk_level: "Critical",
    nearest_expiry: "2026-12-20",
    cold_chain: true,
    beds_available: 3,
    total_beds: 8,
    staff_present: 4,
    staff_sanctioned: 6,
    reporting_status: "reported_today",
    last_updated: "Today, 08:00 AM",
  },

  // KERALA
  {
    phc_id: "PHC-KL-001",
    phc_name: "PHC Meppadi",
    state: "Kerala",
    district: "Wayanad",
    medicine: "Insulin Human NPH 10ml",
    disease_class: "chronic_metabolic",
    stock: 15,
    unit: "vials",
    daily_demand: 6,
    days_of_cover: 2.5,
    risk_level: "Critical",
    nearest_expiry: "2026-11-28",
    cold_chain: true,
    beds_available: 3,
    total_beds: 8,
    staff_present: 6,
    staff_sanctioned: 7,
    reporting_status: "reported_today",
    last_updated: "Today, 09:20 AM",
  },
  {
    phc_id: "PHC-KL-002",
    phc_name: "PHC Sultan Bathery",
    state: "Kerala",
    district: "Wayanad",
    medicine: "Insulin Human NPH 10ml",
    disease_class: "chronic_metabolic",
    stock: 240,
    unit: "vials",
    daily_demand: 5,
    days_of_cover: 48.0,
    risk_level: "Low",
    nearest_expiry: "2026-12-15", // <90 days surplus!
    cold_chain: true,
    beds_available: 7,
    total_beds: 12,
    staff_present: 9,
    staff_sanctioned: 10,
    reporting_status: "reported_today",
    last_updated: "Today, 08:40 AM",
  },
  {
    phc_id: "PHC-KL-001",
    phc_name: "PHC Meppadi",
    state: "Kerala",
    district: "Wayanad",
    medicine: "Metformin 500mg tab",
    disease_class: "chronic_metabolic",
    stock: 210,
    unit: "strips",
    daily_demand: 35,
    days_of_cover: 6.0,
    risk_level: "High",
    nearest_expiry: "2027-03-31",
    cold_chain: false,
    beds_available: 3,
    total_beds: 8,
    staff_present: 6,
    staff_sanctioned: 7,
    reporting_status: "reported_today",
    last_updated: "Today, 09:20 AM",
  },
  {
    phc_id: "PHC-KL-003",
    phc_name: "PHC Vithura",
    state: "Kerala",
    district: "Thiruvananthapuram",
    medicine: "Dextrose 5% 500ml IV",
    disease_class: "emergency_trauma",
    stock: 12,
    unit: "bottles",
    daily_demand: 4,
    days_of_cover: 3.0,
    risk_level: "Critical",
    nearest_expiry: "2027-05-15",
    cold_chain: false,
    beds_available: 4,
    total_beds: 8,
    staff_present: 5,
    staff_sanctioned: 6,
    reporting_status: "reported_today",
    last_updated: "Today, 08:15 AM",
  },

  // ASSAM
  {
    phc_id: "PHC-AS-005",
    phc_name: "PHC Silapathar",
    state: "Assam",
    district: "Dhemaji",
    medicine: "Anti-snake venom vial",
    disease_class: "emergency_trauma",
    stock: 5,
    unit: "vials",
    daily_demand: 3,
    days_of_cover: 1.7,
    risk_level: "Critical",
    nearest_expiry: "2026-11-20",
    cold_chain: true,
    beds_available: 2,
    total_beds: 8,
    staff_present: 5,
    staff_sanctioned: 6,
    reporting_status: "reported_today",
    last_updated: "Today, 07:15 AM",
  },
  {
    phc_id: "PHC-AS-005",
    phc_name: "PHC Silapathar",
    state: "Assam",
    district: "Dhemaji",
    medicine: "ORS sachet",
    disease_class: "diarrhoeal",
    stock: 80,
    unit: "packs",
    daily_demand: 40,
    days_of_cover: 2.0,
    risk_level: "Critical",
    nearest_expiry: "2027-01-30",
    cold_chain: false,
    beds_available: 2,
    total_beds: 8,
    staff_present: 5,
    staff_sanctioned: 6,
    reporting_status: "reported_today",
    last_updated: "Today, 07:15 AM",
  },
  {
    phc_id: "PHC-AS-001",
    phc_name: "PHC Hajo",
    state: "Assam",
    district: "Kamrup",
    medicine: "Anti-snake venom vial",
    disease_class: "emergency_trauma",
    stock: 85,
    unit: "vials",
    daily_demand: 2,
    days_of_cover: 42.5,
    risk_level: "Low",
    nearest_expiry: "2026-12-10", // <90 days surplus!
    cold_chain: true,
    beds_available: 6,
    total_beds: 10,
    staff_present: 6,
    staff_sanctioned: 7,
    reporting_status: "reported_today",
    last_updated: "Today, 08:45 AM",
  },
  {
    phc_id: "PHC-AS-003",
    phc_name: "PHC Lakhipur",
    state: "Assam",
    district: "Cachar",
    medicine: "Artemether + Lumefantrine 20/120 tab",
    disease_class: "fever_vector",
    stock: 60,
    unit: "packs",
    daily_demand: 20,
    days_of_cover: 3.0,
    risk_level: "Critical",
    nearest_expiry: "2027-02-15",
    cold_chain: false,
    beds_available: 4,
    total_beds: 10,
    staff_present: 7,
    staff_sanctioned: 8,
    reporting_status: "reported_today",
    last_updated: "Today, 08:20 AM",
  },
  {
    phc_id: "PHC-AS-004",
    phc_name: "PHC Dholai",
    state: "Assam",
    district: "Cachar",
    medicine: "Artemether + Lumefantrine 20/120 tab",
    disease_class: "fever_vector",
    stock: 950,
    unit: "packs",
    daily_demand: 15,
    days_of_cover: 63.3,
    risk_level: "Low",
    nearest_expiry: "2026-11-25", // <90 days surplus!
    cold_chain: false,
    beds_available: 3,
    total_beds: 6,
    staff_present: 4,
    staff_sanctioned: 5,
    reporting_status: "reported_today",
    last_updated: "Today, 09:10 AM",
  },
];

// 30-day historical + 14-day ARIMA+ forecast time series for Paracetamol 500mg
export interface TimeSeriesPoint {
  day_label: string; // "Day -30" ... "Today" ... "Day +14"
  date: string;
  is_forecast: boolean;
  actual_stock?: number;
  daily_consumption?: number;
  forecast_demand?: number;
  lower_ci_95?: number;
  upper_ci_95?: number;
  stockout_threshold: number;
}

export function generateTrendSeries(medicineName = "Paracetamol 500mg tab"): TimeSeriesPoint[] {
  const points: TimeSeriesPoint[] = [];
  const baseBurn = 180;
  let currentStock = 5400;

  // 30 Historical Days (-30 to Day 0)
  for (let i = 30; i >= 0; i--) {
    const dateObj = new Date();
    dateObj.setDate(dateObj.getDate() - i);
    const dateStr = dateObj.toISOString().slice(5, 10);
    const dayBurn = Math.round(baseBurn + Math.sin(i * 0.4) * 35 + (i < 5 ? 40 : 0));
    currentStock = Math.max(500, currentStock - dayBurn + (i === 15 ? 3000 : 0));

    points.push({
      day_label: i === 0 ? "Today" : `-${i}d`,
      date: dateStr,
      is_forecast: false,
      actual_stock: currentStock,
      daily_consumption: dayBurn,
      stockout_threshold: 600, // 3 days of cover
    });
  }

  // 14 Forecast Days (+1 to +14) with ARIMA+ confidence band
  let projectedStock = currentStock;
  for (let i = 1; i <= 14; i++) {
    const dateObj = new Date();
    dateObj.setDate(dateObj.getDate() + i);
    const dateStr = dateObj.toISOString().slice(5, 10);
    const projectedBurn = Math.round(baseBurn + 30 + i * 8); // rising surge
    projectedStock = Math.max(0, projectedStock - projectedBurn);
    const uncertainty = i * 25;

    points.push({
      day_label: `+${i}d`,
      date: dateStr,
      is_forecast: true,
      forecast_demand: projectedStock,
      lower_ci_95: Math.max(0, projectedStock - uncertainty),
      upper_ci_95: projectedStock + uncertainty,
      stockout_threshold: 600,
    });
  }

  return points;
}

export const INITIAL_TRANSFER_PLANS: TransferPlanItem[] = [
  {
    id: "TR-2026-0929-01",
    state: "Madhya Pradesh",
    from_id: "PHC-MP-003",
    from_name: "PHC Kanadia (Indore)",
    from_district: "Indore",
    from_type: "PHC",
    from_lat: 22.7196,
    from_lon: 75.8577,
    to_id: "PHC-MP-001",
    to_name: "PHC Rampur (Dewas)",
    to_district: "Dewas",
    to_lat: 22.9676,
    to_lon: 76.0534,
    medicine: "Paracetamol 500mg tab",
    quantity: 1200,
    unit: "tablets",
    road_distance_km: 42.0,
    urgency: "Critical",
    one_line_reason: "Rampur drops below 2.5 days of cover during fever surge; Kanadia holds 61 days with surplus expiring in 65 days.",
    watch_out_chips: ["Expiring in 65 days (FEFO)", "Ambient Transit", "Source remains with 53d cover"],
    from_days_before: 61.3,
    from_days_after: 53.3,
    to_days_before: 2.5,
    to_days_after: 8.5,
    status: "PENDING_APPROVAL",
    estimated_stockout_days_avoided: 6,
    estimated_value_inr: 2400,
  },
  {
    id: "TR-2026-0929-02",
    state: "Madhya Pradesh",
    from_id: "PHC-MP-003",
    from_name: "PHC Kanadia (Indore)",
    from_district: "Indore",
    from_type: "PHC",
    from_lat: 22.7196,
    from_lon: 75.8577,
    to_id: "PHC-MP-001",
    to_name: "PHC Rampur (Dewas)",
    to_district: "Dewas",
    to_lat: 22.9676,
    to_lon: 76.0534,
    medicine: "ORS sachet",
    quantity: 300,
    unit: "packs",
    road_distance_km: 42.0,
    urgency: "Critical",
    one_line_reason: "Rampur has only 1.8 days of ORS left; Kanadia has 2800 packs expiring in Nov 2026.",
    watch_out_chips: ["Expiring in 52 days", "Moisture-proof packing"],
    from_days_before: 70.0,
    from_days_after: 62.5,
    to_days_before: 1.8,
    to_days_after: 13.8,
    status: "PENDING_APPROVAL",
    estimated_stockout_days_avoided: 12,
    estimated_value_inr: 4500,
  },
  {
    id: "TR-2026-0929-03",
    state: "Kerala",
    from_id: "PHC-KL-002",
    from_name: "PHC Sultan Bathery (Wayanad)",
    from_district: "Wayanad",
    from_type: "PHC",
    from_lat: 11.6628,
    from_lon: 76.257,
    to_id: "PHC-KL-001",
    to_name: "PHC Meppadi (Wayanad)",
    to_district: "Wayanad",
    to_lat: 11.5546,
    to_lon: 76.1264,
    medicine: "Insulin Human NPH 10ml",
    quantity: 40,
    unit: "vials",
    road_distance_km: 26.5,
    urgency: "Critical",
    one_line_reason: "Meppadi has only 15 insulin vials (2.5 days cover); Sultan Bathery has 48 days buffer.",
    watch_out_chips: ["Cold Chain Required (2°C–8°C)", "Vaccine Carrier with Ice Packs", "Temp Data Logger"],
    from_days_before: 48.0,
    from_days_after: 40.0,
    to_days_before: 2.5,
    to_days_after: 9.1,
    status: "PENDING_APPROVAL",
    estimated_stockout_days_avoided: 7,
    estimated_value_inr: 8800,
  },
  {
    id: "TR-2026-0929-04",
    state: "Assam",
    from_id: "PHC-AS-001",
    from_name: "PHC Hajo (Kamrup)",
    from_district: "Kamrup",
    from_type: "PHC",
    from_lat: 26.2485,
    from_lon: 91.5235,
    to_id: "PHC-AS-005",
    to_name: "PHC Silapathar (Dhemaji)",
    to_district: "Dhemaji",
    to_lat: 27.5931,
    to_lon: 94.7219,
    medicine: "Anti-snake venom vial",
    quantity: 20,
    unit: "vials",
    road_distance_km: 74.0,
    urgency: "Critical",
    one_line_reason: "Silapathar flood surge down to 5 vials (1.7d cover); Hajo holds 85 surplus vials.",
    watch_out_chips: ["Cold Box Required", "River-crossing dispatch", "Flood corridor route"],
    from_days_before: 42.5,
    from_days_after: 32.5,
    to_days_before: 1.7,
    to_days_after: 8.3,
    status: "PENDING_APPROVAL",
    estimated_stockout_days_avoided: 7,
    estimated_value_inr: 15000,
  },
  {
    id: "TR-2026-0929-05",
    state: "Maharashtra",
    from_id: "PHC-MH-002",
    from_name: "PHC Junnar (Pune)",
    from_district: "Pune",
    from_type: "PHC",
    from_lat: 19.2064,
    from_lon: 73.8764,
    to_id: "PHC-MH-003",
    to_name: "PHC Dhadgaon (Nandurbar)",
    to_district: "Nandurbar",
    to_lat: 21.6481,
    to_lon: 74.2251,
    medicine: "Amoxicillin 500mg cap",
    quantity: 800,
    unit: "capsules",
    road_distance_km: 68.0,
    urgency: "High",
    one_line_reason: "Dhadgaon tribal clinic has 4.2 days of Amoxicillin remaining; Junnar warehouse has 45 days surplus.",
    watch_out_chips: ["Moisture Sensitive", "Hill Transit Route"],
    from_days_before: 45.0,
    from_days_after: 37.0,
    to_days_before: 4.2,
    to_days_after: 11.2,
    status: "PENDING_APPROVAL",
    estimated_stockout_days_avoided: 7,
    estimated_value_inr: 3200,
  },
];

export const INITIAL_ALERTS: SupplyAlert[] = [
  {
    id: "ALT-2026-0929-01",
    severity: "Critical",
    title: "Acute Paracetamol Stockout Imminent: PHC Rampur (Dewas)",
    state: "Madhya Pradesh",
    district: "Dewas",
    affected_phcs: ["PHC-MP-001"],
    medicine: "Paracetamol 500mg tab",
    days_of_cover: 2.5,
    recommended_action: "Approve 1,200 tablets inter-facility redistribution from PHC Kanadia (Indore).",
    full_message: "URGENT PUBLIC HEALTH NOTICE: PHC Rampur in Dewas district has 500 Paracetamol tablets remaining with a daily burn rate of 200 tablets (2.5 days of cover). Monsoon fever cases have spiked by 35% in Sonkatch block. Recommend immediate sign-off on Transfer Order #TR-2026-0929-01 from PHC Kanadia.",
    sms_text: "PHC PULSE ALERT: Critical Paracetamol shortage at PHC Rampur, Dewas (2.5d cover left). Inter-district transfer of 1200 tabs from PHC Kanadia ready for CMO approval.",
    status: "Draft",
    timestamp: "Today, 08:35 AM",
  },
  {
    id: "ALT-2026-0929-02",
    severity: "Critical",
    title: "Anti-Snake Venom Stock Depleted: PHC Silapathar (Dhemaji)",
    state: "Assam",
    district: "Dhemaji",
    affected_phcs: ["PHC-AS-005"],
    medicine: "Anti-snake venom vial",
    days_of_cover: 1.7,
    recommended_action: "Deploy cold-box emergency dispatch of 20 vials from PHC Hajo.",
    full_message: "CRITICAL ALERT: PHC Silapathar in Dhemaji has only 5 vials of anti-snake venom remaining amid rising Brahmaputra floodwaters. Average snakebite rate is 3 bites/day. Buffer will exhaust in 40 hours. Cold chain transport vehicle requested.",
    sms_text: "URGENT: Anti-snake venom at PHC Silapathar, Dhemaji down to 5 vials (1.7d). 20 vials transfer from PHC Hajo awaiting approval.",
    status: "Draft",
    timestamp: "Today, 07:20 AM",
  },
  {
    id: "ALT-2026-0929-03",
    severity: "Critical",
    title: "Cold Chain Insulin Buffer Breach: PHC Meppadi (Wayanad)",
    state: "Kerala",
    district: "Wayanad",
    affected_phcs: ["PHC-KL-001"],
    medicine: "Insulin Human NPH 10ml",
    days_of_cover: 2.5,
    recommended_action: "Approve 40 vials transfer from PHC Sultan Bathery with temperature logger.",
    full_message: "WARNING: PHC Meppadi insulin stock down to 15 vials serving 48 chronic type-1 & type-2 diabetic patients. Nearest district warehouse replenishment delayed 4 days. Inter-facility transfer needed immediately.",
    sms_text: "PHC PULSE: Insulin Human NPH low at PHC Meppadi (2.5d). Transfer of 40 vials from Sultan Bathery pending CMO approval.",
    status: "Draft",
    timestamp: "Today, 09:25 AM",
  },
];

export const INITIAL_FEDERATED_METRICS: FederatedMetrics = {
  current_round: 54,
  last_aggregation_timestamp: "Today, 06:00 AM UTC",
  state_nodes: [
    {
      state: "Madhya Pradesh",
      node_id: "NODE-MP-CENTRAL",
      phc_count: 58,
      last_training_round: 54,
      local_mape_before: 24.6,
      local_mape_after: 16.2,
      accuracy_gain_pct: 18.4,
      status: "SYNCED",
      recent_learned_insight: "Learned Kerala's leptospirosis dual-wave pattern; gained 16.8 days earlier fever surge notification.",
    },
    {
      state: "Maharashtra",
      node_id: "NODE-MH-WEST",
      phc_count: 52,
      last_training_round: 54,
      local_mape_before: 22.8,
      local_mape_after: 15.6,
      accuracy_gain_pct: 15.2,
      status: "SYNCED",
      recent_learned_insight: "Calibrated winter viral influenza spike from urban Pune to tribal Nandurbar clinics.",
    },
    {
      state: "Kerala",
      node_id: "NODE-KL-SOUTH",
      phc_count: 44,
      last_training_round: 54,
      local_mape_before: 21.0,
      local_mape_after: 14.1,
      accuracy_gain_pct: 19.1,
      status: "SYNCED",
      recent_learned_insight: "Enhanced cold-chain insulin wastage prediction during coastal humidity & high temperature anomalies.",
    },
    {
      state: "Assam",
      node_id: "NODE-AS-EAST",
      phc_count: 46,
      last_training_round: 54,
      local_mape_before: 28.5,
      local_mape_after: 17.8,
      accuracy_gain_pct: 21.0,
      status: "SYNCED",
      recent_learned_insight: "Adopted Madhya Pradesh's vector spike coefficients for pre-flood anti-venom pre-positioning.",
    },
  ],
  rounds_history: [
    { round: 10, global_mape: 29.2, accuracy_pct: 70.8 },
    { round: 20, global_mape: 25.1, accuracy_pct: 74.9 },
    { round: 30, global_mape: 21.4, accuracy_pct: 78.6 },
    { round: 40, global_mape: 18.2, accuracy_pct: 81.8 },
    { round: 50, global_mape: 16.5, accuracy_pct: 83.5 },
    { round: 54, global_mape: 15.9, accuracy_pct: 84.1 },
  ],
};
